name: CI
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
         python -m pip install --upgrade pip
         pip install -r requirements.txt

    - name: run TRANSLATOR unit tests
      run: |
        python -m unittest -v -b test/unittests/translator/TestTranslator.py 

    - name: run MODEL unit tests
      run: |
        python -m unittest -v -b test/unittests/model/TestModel.py

    - name: run golden tests TRANSLATOR
      run: |
        python -m unittest -v -b test/golden/TestAllGoldenTranslator.py

#    - name: run golden tests MODEL
#      run: |
#        python -m unittest -v -b test/golden/TestAllGoldenModel.py
#
#    - name: run integrational tests
#      run: |
#        python -m unittest -v -b test/integrational/TestAll.py
