name: CI
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
         python -m pip install --upgrade pip
         pip install -r requirements.txt
        
    - name: test translator
      run: |
        python -m unittest -v -b test/unittests/TestTranslator.py 

    - name: test simulation
      run: |
        python -m unittest -v -b test/unittests/TestSimulation.py 

    - name: test golden tests
      run: |
        pytest 

    - name: test integration
      run: |
        python -m unittest -v -b test/integrational/TestAll.py 
